import { useEffect, useMemo, useState } from "react";
import { Search, Download, Mail, MessageCircle, RefreshCw, BookOpen } from "lucide-react";
import "./PartyLedgerPage.css";

const API = import.meta.env.VITE_API_URL || "http://localhost:3001";
function authHeaders(){ const t=localStorage.getItem("raildesk_auth_token"); return t ? {Authorization:"Bearer "+t} : {}; }
const money=v=>"₹"+Number(v||0).toLocaleString("en-IN",{minimumFractionDigits:2,maximumFractionDigits:2});

export default function PartyLedgerPage(){
 const [parties,setParties]=useState([]),[partyId,setPartyId]=useState(""),[query,setQuery]=useState(""),[ledger,setLedger]=useState(null),[loading,setLoading]=useState(false),[error,setError]=useState("");
 useEffect(()=>{fetch(API+"/api/parties",{credentials:"include",headers:authHeaders()}).then(r=>r.json()).then(d=>setParties(d.parties||[])).catch(()=>{})},[]);
 async function load(id=partyId){ if(!id)return; setLoading(true);setError(""); try{const r=await fetch(API+"/api/reports/party-ledger/"+encodeURIComponent(id),{credentials:"include",headers:authHeaders()});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.message||"Unable to load ledger.");setLedger(d)}catch(e){setError(e.message||"Unable to load ledger.")}finally{setLoading(false)} }
 const filtered=useMemo(()=>{const q=query.toLowerCase().trim();return parties.filter(p=>!q||[p.customerName,p.whatsapp,p.email,p.city].some(v=>String(v||"").toLowerCase().includes(q)))},[parties,query]);
 function download(){if(!ledger)return;const rows=[["Date","Description","Reference","DR","CR","Balance"],...ledger.ledger.map(e=>[e.date,e.description,e.reference,e.dr,e.cr,e.balance])];const csv=rows.map(r=>r.map(v=>"""+String(v??"").replaceAll(""","""")+""").join(",")).join("\n");const blob=new Blob([csv],{type:"text/csv;charset=utf-8"});const u=URL.createObjectURL(blob);const x=document.createElement("a");x.href=u;x.download=(ledger.party.customerName||"party")+"-ledger.csv";x.click();URL.revokeObjectURL(u)}
 function email(){if(!ledger)return;const s=encodeURIComponent("Party Ledger - "+ledger.party.customerName),b=encodeURIComponent("Party Ledger\nTotal DR: "+money(ledger.totalDr)+"\nTotal CR: "+money(ledger.totalCr)+"\nBalance: "+money(ledger.balance));location.href="mailto:"+(ledger.party.email||"")+"?subject="+s+"&body="+b}
 function whatsapp(){if(!ledger)return;const t=encodeURIComponent("Party Ledger - "+ledger.party.customerName+"\nDR: "+money(ledger.totalDr)+"\nCR: "+money(ledger.totalCr)+"\nBalance: "+money(ledger.balance));window.open("https://wa.me/?text="+t,"_blank","noopener,noreferrer")}
 return <main className="content party-ledger-page"><div className="module-page-header ledger-head"><div><div className="eyebrow">REPORTS / PARTY LEDGER</div><h1>Party Ledger <span>✦</span></h1><p>Complete party-wise DR / CR / Balance statement.</p></div>{ledger&&<div className="ledger-actions"><button onClick={email}><Mail size={14}/> Send Email</button><button onClick={whatsapp}><MessageCircle size={14}/> Send WhatsApp</button><button onClick={download}><Download size={14}/> Download</button></div>}</div>
 <section className="ledger-filter"><div className="party-search"><Search size={15}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search party name, WhatsApp, email or city..."/></div><select value={partyId} onChange={e=>{setPartyId(e.target.value);load(e.target.value)}}><option value="">Choose Party</option>{filtered.map(p=><option key={p.id} value={p.id}>{p.customerName}</option>)}</select><button className="ledger-refresh" onClick={()=>load()} disabled={!partyId||loading}><RefreshCw size={14}/> Refresh</button></section>
 {error&&<div className="ledger-error">{error}</div>}{!ledger&&!loading&&<div className="ledger-empty"><BookOpen size={34}/><b>Choose a Party</b><span>Select a party to view the complete ledger.</span></div>}
 {ledger&&<><section className="party-summary"><div><small>PARTY</small><b>{ledger.party.customerName}</b><span>{ledger.party.whatsapp||ledger.party.email||ledger.party.city||"Customer"}</span></div><div><small>TOTAL DR</small><b>{money(ledger.totalDr)}</b><span>Ticket Bookings</span></div><div><small>TOTAL CR</small><b>{money(ledger.totalCr)}</b><span>Payments Received</span></div><div><small>BALANCE</small><b>{money(ledger.balance)}</b><span>{ledger.balance>0?"Amount Due":ledger.balance<0?"Advance":"Settled"}</span></div></section>
 <section className="ledger-card"><div className="ledger-title"><span>Transaction Ledger</span><small>{ledger.ledger.length} entries</small></div><div className="ledger-table-wrap"><table className="ledger-table"><thead><tr><th>#</th><th>Date</th><th>Description</th><th>Reference / PNR</th><th className="amt">DR</th><th className="amt">CR</th><th className="amt">Balance</th></tr></thead><tbody>{ledger.ledger.length===0?<tr><td colSpan="7" className="ledger-empty-row">No transactions found.</td>:ledger.ledger.map(e=><tr key={e.id}><td>{e.sr}</td><td>{e.date}</td><td><b>{e.description}</b></td><td>{e.reference}</td><td className="amt dr">{e.dr?money(e.dr):"—"}</td><td className="amt cr">{e.cr?money(e.cr):"—"}</td><td className="amt balance">{money(e.balance)}</td></tr>)}</tbody><tfoot><tr><td colSpan="4">TOTAL</td><td className="amt dr">{money(ledger.totalDr)}</td><td className="amt cr">{money(ledger.totalCr)}</td><td className="amt balance">{money(ledger.balance)}</td></tr></tfoot></table></div></section></>}</main>
}